// Lightweight, on-site fallback movies rendered instantly while the backend loads
// Keep this list small to ensure fast initial paint

import { Download } from 'lucide-react';

const staticMovies = [
  {
    id: 'prosecutor1',
    title: 'PROSECUTOR',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/prosecutorw.webp',
    poster_url: '/prosecutor (1).webp',
    image_url: '/prosecutor (1).webp',
    video_url: 'https://hglink.to/dewt0sayiyiw',
    download_url:
      'https://www.mediafire.com/file/yzf9j1qj1qs933t/THE_PROSECUTOR.mp4/file',
    youtube_trailer_url: 'https://hglink.to/dewt0sayiyiw',
  },

  {
    id: 'war2Rocky',
    title: 'WAR 2 B (ROCKY)',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    is_featured: true,
    interpreter_name: 'ROCKY',
    // created_at: '2025-10-04',
    thumbnail_url: '/war2x.webp',
    poster_url: '/war2x.webp',
    image_url: '/war2x.webp',
    video_url: 'https://hglink.to/gytjayfhqh5u',
    download_url:
      'https://www.mediafire.com/file/mnj7klva93qvf8a/WAR2+B.mp4/file',
    youtube_trailer_url: 'https://hglink.to/gytjayfhqh5u',
  },

  {
    id: 'war2BTHEGREAT',
    title: 'WAR 2 (full movie)',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    is_popular: true,
    is_featured: true,
    interpreter_name: 'B THE GREAT',
    // created_at: '2025-10-04',
    thumbnail_url: '/war2x.webp',
    poster_url: '/war2x.webp',
    image_url: '/war2x.webp',
    video_url: 'https://hglink.to/hrfc8cuv5g69',
    download_url:
      'https://www.mediafire.com/file/bionm69aqa5sovq/WAR+2+gahezaa.mp4/file',
    youtube_trailer_url: 'https://hglink.to/hrfc8cuv5g69',
  },
  {
    id: 'war2',
    title: 'WAR 2 A',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    is_popular: true,
    interpreter_name: 'ROCKY',
    // created_at: '202-10-04',
    thumbnail_url: '/war2x.webp',
    poster_url: '/war2x.webp',
    image_url: '/war2x.webp',
    video_url: 'https://hglink.to/sn9ef5jan7nf',
    download_url:
      'https://www.mediafire.com/file/7eybkr913j5j7wr/WAR+2.mp4/file',
    youtube_trailer_url: 'https://hglink.to/sn9ef5jan7nf',
  },
   {
    id: 'indecent_proposal',
    title: 'INDECENT PROPOSAL',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    is_popular:true,
    interpreter_name: 'YANGA',
    created_at: '2025-10-04',
    thumbnail_url: '/indecent.webp',
    poster_url: '/indecent.webp',
    image_url: '/indecent.webp',
    video_url: 'https://hglink.to/pase3wvzueqy',
    download_url:'https://www.mediafire.com/file/v18q8xxs3x3e4v8/INDECENT_PROPOSAL.mp4/file',
    youtube_trailer_url: 'https://hglink.to/pase3wvzueqy',
  },

   {
    id: 'sky_in_the_next_door',
    title: 'SKY IN THE NEXT DOOR',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    is_popular:true,
    interpreter_name: 'YANGA',
    created_at: '2025-10-04',
    thumbnail_url: '/spy.webp',
    poster_url: '/spy.webp',
    image_url: '/spy.webp',
    video_url: 'https://hglink.to/mpoobmvp6zql',
    download_url:'https://www.mediafire.com/file/bd1f28viih5agrh/SPY_IN_THE_NEXT_DOOR.mp4.mp4/file',
    youtube_trailer_url: 'https://hglink.to/mpoobmvp6zql',
  },

   {
    id: 'naked_weapon',
    title: 'NAKED WEAPON',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    is_popular:true,
    interpreter_name: 'YANGA',
    created_at: '2025-10-04',
    thumbnail_url: '/naked_weapon.webp',
    poster_url: '/naked_weapon.webp',
    image_url: '/naked_weapon.webp',
    video_url: 'https://hglink.to/3jl1582lqhqs',
    download_url:'https://www.mediafire.com/file/5vrrj16mz1so3ei/Naked+Weapon.mp4/file',
    youtube_trailer_url: 'https://hglink.to/3jl1582lqhqs',
  },

    {
    id: 'state_of_the_union',
    title: 'XXX STATE OF THE UNION',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    is_popular:true,
    interpreter_name: 'YANGA',
    created_at: '2025-10-04',
    thumbnail_url: '/state_of_union.webp',
    poster_url: '/state_of_union.webp',
    image_url: '/state_of_union.webp',
    video_url: 'https://hglink.to/sj3hyivl086v',
    download_url:'https://www.mediafire.com/file/gfwvgtt5mx3fj09/XXX+State+Of+The+Union.mp4/file',
    youtube_trailer_url: 'https://hglink.to/sj3hyivl086v',
  },

    {
    id: 'the_hard_corps',
    title: 'THE HARD CORPS',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    is_popular:true,
    interpreter_name: 'YANGA',
    created_at: '2025-10-04',
    thumbnail_url: '/hard_corps.webp',
    poster_url: '/hard_corps.webp',
    image_url: '/hard_corps.webp',
    video_url: 'https://hglink.to/fle9504jici5',
    download_url:'https://www.mediafire.com/file/ro7kq1lxw08sfb6/The+Hard+Corps.mp4/file',
    youtube_trailer_url: 'https://hglink.to/fle9504jici5',
  },

    {
    id: 'money_train',
    title: 'MONEY TRAIN',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    is_popular:true,
    interpreter_name: 'YANGA',
    created_at: '2025-10-04',
    thumbnail_url: '/money_train.webp',
    poster_url: '/money_train.webp',
    image_url: '/money_train.webp',
    video_url: 'https://hglink.to/kmqh5q00rwon',
    download_url:'https://www.mediafire.com/file/sga5jadzdy2d2b5/Money+Train.mp4/file',
    youtube_trailer_url: 'https://hglink.to/kmqh5q00rwon',
  },

    {
    id: 'note_book',
    title: 'NOTE BOOK',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    is_popular:true,
    interpreter_name: 'YANGA',
    created_at: '2025-10-04',
    thumbnail_url: '/note_book.webp',
    poster_url: '/note_book.webp',
    image_url: '/note_book.webp',
    video_url: 'https://hglink.to/0dxt822wdes7',
    download_url:'https://www.mediafire.com/file/0rqke1gk5arjq0w/Note+Book.mp4/file',
    youtube_trailer_url: 'https://hglink.to/0dxt822wdes7',
  },

    {
    id: 'die_another_day',
    title: 'DIE ANOTHER DAY',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    is_popular:true,
    interpreter_name: 'YANGA',
    created_at: '2025-10-04',
    thumbnail_url: '/die_another.webp',
    poster_url: '/die_another.webp',
    image_url: '/die_another.webp',
    video_url: 'https://hglink.to/ww9js2nsq1ur',
    download_url:'https://www.mediafire.com/file/452x1zzwunfipsn/Die+Another+Day.mp4/file',
    youtube_trailer_url: 'https://hglink.to/ww9js2nsq1ur',
  },

    {
    id: 'saaho',
    title: 'SAAHO',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    is_popular:true,
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/saaho.webp',
    poster_url: '/saaho.webp',
    image_url: '/saaho.webp',
    video_url: 'https://hglink.to/bwy770t7c7wk',
    download_url:'https://www.mediafire.com/file/0zrhib7dwf5y6n0/SAAHO.mp4/file',
    youtube_trailer_url: 'https://hglink.to/bwy770t7c7wk',
  },






     {
    id: 'killration',
    title: 'KILL RATIO',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    is_featured: true,
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/killra.webp',
    poster_url: '/killra.webp',
    image_url: '/killra.webp',
    video_url: 'https://hglink.to/vg3cs6pzh37l',
    download_url:
      'https://www.mediafire.com/file/0201g0ewvvimsv6/Kill+Ratio.mp4/file',
    youtube_trailer_url: 'https://hglink.to/vg3cs6pzh37l',
  },

  {
    id: 'FighterA',
    title: 'FIGHTER A',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/fighter-indian-movie-poster-md.webp',
    poster_url: '/fighter-indian-movie-poster-md.webp',
    image_url: '/fighter-indian-movie-poster-md.webp',
    video_url: 'https://hglink.to/ke18haht0wnn',
    download_url:
      'https://www.mediafire.com/file/qxlx2yr7x7m19qx/FIGHTER_A.mp4/file',
    youtube_trailer_url: 'https://hglink.to/ke18haht0wnn',
  },

  {
    id: 'FighterB',
    title: 'FIGHTER B',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/fighter-indian-movie-poster-md.webp',
    poster_url: '/fighter-indian-movie-poster-md.webp',
    image_url: '/fighter-indian-movie-poster-md.webp',
    video_url: 'https://hglink.to/ib9sndodh4lw',
    download_url:
      'https://www.mediafire.com/file/noy8uv9wojv3u3j/FIGHTER_B.mp4/file',
    youtube_trailer_url: 'https://hglink.to/ib9sndodh4lw',
  },

  {
    id: 'karatelegends1',
    title: 'KARATE KID LEGENDS A',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/karate.webp',
    poster_url: '/karate.webp',
    image_url: '/karate.webp',
    video_url: 'https://hglink.to/j6r6j4hs7xue',
    download_url:
      'https://www.mediafire.com/file/2xr4wo8rb6mxras/KARATE+KID+LEGENDS+A.mp4/file',
    youtube_trailer_url: 'https://hglink.to/j6r6j4hs7xue',
  },

  {
    id: 'karatelegends2',
    title: 'KARATE KID LEGENDS B',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/karate.webp',
    poster_url: '/karate.webp',
    image_url: '/karate.webp',
    video_url: 'https://hglink.to/pkwzmsvusvpt',
    download_url:
      'https://www.mediafire.com/file/xyhnvfmhc6lar5t/KARATE+KID+LEGENDS+B.mp4/file',
    youtube_trailer_url: 'https://hglink.to/pkwzmsvusvpt',
  },

  {
    id: 'salaar',
    title: 'SALAAR A',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/salaar.webp',
    poster_url: '/salaar.webp',
    image_url: '/salaar.webp',
    video_url: 'https://hglink.to/u0cs9wj5xggn',
    download_url:
      'https://www.mediafire.com/file/x22k50joappv304/SALAAR+A..mp4/file',
    youtube_trailer_url: 'https://hglink.to/u0cs9wj5xggn',
  },
  {
    id: 'salaar',
    title: 'SALAAR B',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/salaar.webp',
    poster_url: '/salaar.webp',
    image_url: '/salaar.webp',
    video_url: 'https://hglink.to/e79mqvg4uz7s',
    download_url:
      'https://www.mediafire.com/file/81ux1aj4a76l8eq/SALAAR+B.mp4/file',
    youtube_trailer_url: 'https://hglink.to/e79mqvg4uz7s',
  },
  {
    id: 'salaar',
    title: 'SALAAR C',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/salaar.webp',
    poster_url: '/salaar.webp',
    image_url: '/salaar.webp',
    video_url: 'https://hglink.to/e79mqvg4uz7s',
    download_url:
      'https://www.mediafire.com/file/fp24r1rvhhiqv53/SALAAR+C.mp4/file',
    youtube_trailer_url: 'https://hglink.to/e79mqvg4uz7s',
  },

  {
    id: 'shaitan',
    title: 'SHAITAN',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/shaitan.webp',
    poster_url: '/shaitan.webp',
    image_url: '/shaitan.webp',
    video_url: 'https://hglink.to/hihivlpcjrep',
    download_url:
      'https://www.mediafire.com/file/t33qjmgq76knk58/SHAITAAN.mp4/file',
    youtube_trailer_url: 'https://hglink.to/hihivlpcjrep',
  },
  {
    id: 'adulters',
    title: 'ADULTERS',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/adulters.webp',
    poster_url: '/adulters.webp',
    image_url: '/adulters.webp',
    video_url: 'https://hglink.to/t8t1mv1gyv6a',
    download_url:
      'https://www.mediafire.com/file/5e2b92b030xddjg/ADULTERERS.mp4/file',
    youtube_trailer_url: 'https://hglink.to/t8t1mv1gyv6a',
  },
  {
    id: 'coming',
    title: 'COMING 2 AMARICA 2',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/coming.webp',
    poster_url: '/coming.webp',
    image_url: '/coming.webp',
    video_url: 'https://hglink.to/d39arnawpbgv',
    download_url:
      'https://www.mediafire.com/file/p7xb6z3on1itu43/COMMING_2_AMERICA.mp4/file',
    youtube_trailer_url: 'https://hglink.to/d39arnawpbgv',
  },
  {
    id: 'oldguard',
    title: 'OLD GUARD',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/old.webp',
    poster_url: '/old.webp',
    image_url: '/old.webp',
    video_url: 'https://hglink.to/qlpcl0l91lw0',
    download_url:
      'https://www.mediafire.com/file/as8q4oebqbzvsj5/OLD_GUARD_A.mp4/file',
    youtube_trailer_url: 'https://hglink.to/qlpcl0l91lw0',
  },
  {
    id: 'secretsuper',
    title: 'THE SECRET SUPER STAR',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/superstar.webp',
    poster_url: '/superstar.webp',
    image_url: '/superstar.webp',
    video_url: 'https://hglink.to/8mw720m2poay',
    download_url:
      'https://www.mediafire.com/file/j90as08e8deiuhc/The_Secret_Superstar.mp4/file',
    youtube_trailer_url: 'https://hglink.to/8mw720m2poay',
  },

  {
    id: 'RRR1',
    title: 'RRR A',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/rrr1.webp',
    poster_url: '/rrr1.webp',
    image_url: '/rrr1.webp',
    video_url: 'https://hglink.to/atyjg72uxyx5',
    download_url:
      'https://www.mediafire.com/file/coif4tojeqfvsrd/RRR+A.mp4/file',
    youtube_trailer_url: 'https://hglink.to/atyjg72uxyx5',
  },

  {
    id: 'RRR1',
    title: 'RRR B',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/rrr1.webp',
    poster_url: '/rrr1.webp',
    image_url: '/rrr1.webp',
    video_url: 'https://hglink.to/7fn5dtlc6cvo',
    download_url:
      'https://www.mediafire.com/file/gaa0f7qth2sn0tk/RRR+B.mp4/file',
    youtube_trailer_url: 'https://hglink.to/7fn5dtlc6cvo',
  },

  {
    id: 'MAHARSHI',
    title: 'MAHARSHI',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/MAHARSHI.webp',
    poster_url: '/MAHARSHI.webp',
    image_url: '/MAHARSHI.webp',
    video_url: 'https://hglink.to/9h3a3y108u3v',
    download_url:
      'https://www.mediafire.com/file/2w0iraho9vd9591/MAHARSHI.mp4.mp4/file',
    youtube_trailer_url: 'https://hglink.to/9h3a3y108u3v',
  },

  {
    id: 'thosewhowishmedead',
    title: 'THOSE WHO WISH  ME DEAD',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-10-04',
    thumbnail_url: '/thosewhomedead.webp',
    poster_url: '/thosewhomedead.webp',
    image_url: '/thosewhomedead.webp',
    video_url: 'https://hglink.to/952e83snm8gk',
    download_url:
      'https://www.mediafire.com/file/1mqnl4u47b88s1o/THOSE+WHO+WISH+ME+DEAD.mp4/file ',
    youtube_trailer_url: 'https://hglink.to/952e83snm8gk',
  },

  {
    id: 'Baywatchii',
    title: 'BAYWATCH',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    is_popular: true,
    created_at: '2025-10-04',
    thumbnail_url: '/baywatch.webp',
    poster_url: '/baywatch.webp',
    image_url: '/baywatch.webp',
    video_url: 'https://hglink.to/1f8d4rj3oe01',
    download_url:
      'https://www.mediafire.com/file/dz8bm3x18qpz3wj/BAYWATCH_2.mp4/file',
    youtube_trailer_url: 'https://hglink.to/1f8d4rj3oe01',
  },
  {
    id: 'ADVITAMA',
    title: 'AD VITAM A',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    is_popular: true,
    created_at: '2025-10-04',
    thumbnail_url: '/AdVitamggg.webp',
    poster_url: '/AdVitamggg.webp',
    image_url: '/AdVitamggg.webp',
    video_url: 'https://hglink.to/2xba87fao8lc',
    download_url:
      'https://www.mediafire.com/file/xd9ayn1m1ulwq4r/AD+VITAM+A.mp4/file',
    youtube_trailer_url: 'https://hglink.to/2xba87fao8lci',
  },
  {
    id: 'ADVITAMB',
    title: 'ADVITAM B',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-02-12T00:00:00.000Z',
    thumbnail_url: '/advitam.webp',
    poster_url: '/advitam.webp',
    image_url: '/advitam.webp',
    video_url: 'https://hglink.to/xpnx4ivj503i',
    download_url:
      'https://www.mediafire.com/file/z1pubg77v3u09yl/AD+VITAM+B.mp4/file',
    youtube_trailer_url: 'https://hglink.to/xpnx4ivj503i',
  },
  {
    id: 'Gentlemen',
    title: 'GENTLEMAN',
    description: 'Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    is_popular: true,
    created_at: '2025-02-12T00:00:00.000Z',
    thumbnail_url: '/Gentleman.webp',
    poster_url: '/Gentleman.webp',
    image_url: '/Gentleman.webp',
    video_url: 'https://hglink.to/9c89fnsyh1rh',
    download_url:
      'https://www.mediafire.com/file/84ko5ya7mcz4hxn/GENTLEMAN.mp4/file',
    youtube_trailer_url: 'https://hglink.to/9c89fnsyh1rh',
  },

  {
    id: 'TOHSTAN',
    title: 'OPERATION DUMBO DROP',
    description: 'Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    is_popular: true,
    created_at: '2025-02-12T00:00:00.000Z',
    thumbnail_url: '/operation dumb drop.webp',
    poster_url: '/operation dumb drop.webp',
    image_url: '/operation dumb drop.webp',
    video_url: 'https://hglink.to/5a97bb9fnyn1',
    download_url:
      'https://www.mediafire.com/file/dtxnc3h4wwwlhti/Operation_Dumbo_Drop.mp4/file',
    youtube_trailer_url: 'https://hglink.to/5a97bb9fnyn1',
  },

  {
    id: 'Olastmen',
    title: 'OUR LAST MEN IN PHILIPINE',
    description:
      'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 🔥😁',
    interpreter_name: 'ROCKY',
    created_at: '2025-02-12T00:00:00.000Z',
    thumbnail_url: '/our-last-men-in-the-philippines.webp',
    poster_url: '/our-last-men-in-the-philippines.webp',
    image_url: '/our-last-men-in-the-philippines.webp',
    video_url: 'https://hglink.to/3y4crml6mw22',
    download_url:
      'https://www.mediafire.com/file/bdq0gjx5rr0mutl/OUR+LAST+MEN+IN+PHILIPINE.mp4/file ',
    youtube_trailer_url: 'https://hglink.to/3y4crml6mw22',
  },

  {
    id: 'ACLOD-A',
    title: 'A COLD LIGHT OF A DAY A',
    description:
      'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 🔥😁',
    interpreter_name: 'ROCKY',
    created_at: '2025-02-12T00:00:00.000Z',
    thumbnail_url: '/cold_light_of_day_movie.webp',
    poster_url: '/cold_light_of_day_movie.webp',
    image_url: '/cold_light_of_day_movie.webp',
    video_url: 'https://hglink.to/0b3grorxg43q',
    download_url:
      'https://www.mediafire.com/file/88f355r0ck67t2j/A+COLD+LIGHT+OF+A+DAY+A.mp4/file',
    youtube_trailer_url: 'https://hglink.to/0b3grorxg43q',
  },

  {
    id: 'ACLOD-B',
    title: 'A COLD LIGHT OF A DAY B',
    description:
      'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 🔥😁',
    interpreter_name: 'ROCKY',
    created_at: '2025-02-12T00:00:00.000Z',
    thumbnail_url: '/cold_light_of_day_movie.webp',
    poster_url: '/cold_light_of_day_movie.webp',
    image_url: '/cold_light_of_day_movie.webp',
    video_url: 'https://hglink.to/ndktyxs9kgur',
    download_url:
      'https://www.mediafire.com/file/xtilp7cqe6mt77a/A+COLD+LIGHT+OF+A+DAY+B.mp4/file ',
    youtube_trailer_url: 'https://hglink.to/ndktyxs9kgur',
  },

  {
    id: 'AUGUSTRUSH',
    title: 'AUGAST RUSH',
    description:
      'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 🔥😁',
    interpreter_name: 'ROCKY',
    created_at: '2025-02-12T00:00:00.000Z',
    thumbnail_url: '/augast rush.webp',
    poster_url: '/augast rush.webp',
    image_url: '/augast rush.webp',
    video_url: 'https://hglink.to/suu5tn70ldjy',
    download_url:
      'https://www.mediafire.com/file/1pie9r25ncl8sbr/AUGAST+RUSH.mp4/file',
    youtube_trailer_url: 'https://hglink.to/suu5tn70ldjy',
  },

  {
    id: 'BEHAPPY1',
    title: 'BE HAPPY ',
    description: 'aga filime karangira!!! Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    is_featured: true,
    created_at: '2025-02-12T00:00:00.000Z',
    thumbnail_url: '/behappy.webp',
    poster_url: '/behappy.webp',
    image_url: '/behappy.webp',
    video_url: 'https://hglink.to/6oexv9u81a9e',
    download_url:
      'https://www.mediafire.com/file/7ptesa8g3g1k12h/BE+HAPPY.mp4/file',
    youtube_trailer_url: 'https://hglink.to/6oexv9u81a9e',
  },

  {
    id: '1013CC',
    title: 'THUGS OF HINDUSRAN A',
    description: 'Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-02-12T00:00:00.000Z',
    thumbnail_url: '/thugs  of hindustan (3).webp',
    poster_url: '/thugs  of hindustan (3).webp',
    image_url: '/thugs  of hindustan (3).webp',
    video_url: 'https://hglink.to/79yekzzd6ire',
    download_url:
      'https://www.mediafire.com/file/23y4z76n0h9otov/THUGS_OF_HINDUSTAN_A.mp4/file',
    youtube_trailer_url: 'https://hglink.to/79yekzzd6ire',
  },

  {
    id: '1013Cw',
    title: 'THUGS OF HINDUSRAN B',
    description: 'Aka kararenze ni Ntikagucike.... 😊',
    interpreter_name: 'ROCKY',
    created_at: '2025-02-12T00:00:00.000Z',
    thumbnail_url: '/thugs  of hindustan (3).webp',
    poster_url: '/thugs  of hindustan (3).webp',
    image_url: '/thugs  of hindustan (3).webp',
    video_url: 'https://hglink.to/weoe00jwtjch',
    download_url:
      'https://www.mediafire.com/file/2fa2mjd5ibcrwb2/THUGS_OF_HINDUSTAN_B.mp4/file',
    youtube_trailer_url:
      'https://hglink.to/e/weoe00jwtjch<IFRAME SRC="https://hglink.to/e/weoe00jwtjch" FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO WIDTH=640 HEIGHT=360 allowfullscreen></IFRAME>',
  },

  {
    id: '10137',
    title: 'THE BEE KEEPER A',
    description: 'Amazing movie Ntigucike.... 😊',
    interpreter_name: 'B THE GREAT',
    created_at: '2025-02-12T00:00:00.000Z',
    thumbnail_url: '/THE BEE K.webp',
    poster_url: '/THE BEE K.webp',
    image_url: '/THE BEE K.webp',
    video_url: 'https://hglink.to/nfnwh440h23q',
    download_url:
      'https://www.mediafire.com/file/56fi3jcrlfc40f6/THE_BEEKEEPER_A.mp4/file',
    youtube_trailer_url: 'https://hglink.to/nfnwh440h23q',
  },

  {
    id: '10138',
    title: 'THE BEE KEEPER B',
    description: 'Amazing movie Ntigucike.... 😊',
    interpreter_name: 'B THE GREAT',
    created_at: '2025-02-12T00:00:00.000Z',
    thumbnail_url: '/THE BEE K.webp',
    poster_url: '/THE BEE K.webp',
    image_url: '/THE BEE K.webp',
    video_url: 'https://hglink.to/c5jsc43rmldn',
    download_url:
      'https://www.mediafire.com/file/7p27csfyvu1k9a6/THE_BEEKEEPER_B.mp4/file',
    youtube_trailer_url: 'https://hglink.to/c5jsc43rmldn',
  },

  {
    id: '101211',
    title: 'HAVOC',
    description: 'Amazing movie Ntigucike.... 😊',
    interpreter_name: 'B THE GREAT',
    created_at: '2025-02-12T00:00:00.000Z',
    is_popular: true,
    is_featured: true,
    thumbnail_url: '/havoc.webp',
    poster_url: '/havoc.webp',
    image_url: '/havoc.webp',
    video_url: 'https://hglink.to/klupma9fk47s',
    download_url:
      'https://www.mediafire.com/file/gmu8xnumvitblyb/HAVOC.mp4/file',
    youtube_trailer_url: 'https://youtu.be/YTqc6KRBy4o?si=oW9CNAgR5KszlHaO',
  },

  {
    id: 's41',
    title: 'Heads of State A',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    // created_at: '2025-08-30T00:00:00.000Z',
    //  is_popular: true,
    thumbnail_url: '/heads.jpg',
    poster_url: '/heads.jpg',
    image_url: '/heads.jpg',
    video_url: 'https://hglink.to/i6331zcdqx8n',
    download_url:
      'https://www.mediafire.com/file/j7bc59ac7zmwm2f/HEADS_OF_STATE_A.mp4/file',
    youtube_trailer_url: 'https://hglink.to/i6331zcdqx8n',
  },

  {
    id: 's41 headsB',
    title: 'Heads of State B',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    // created_at: '2025-08-30T00:00:00.000Z',
    //  is_popular: true,
    thumbnail_url: '/heads.jpg',
    poster_url: '/heads.jpg',
    image_url: '/heads.jpg',
    video_url: 'https://hglink.to/i6331zcdqx8n',
    download_url:
      'https://www.mediafire.com/file/96b2klf0r9mnt9o/HEADS_OF_STATE_B.mp4/file',
    youtube_trailer_url: 'https://hglink.to/i6331zcdqx8n',
  },

  {
    id: '10146',
    title: 'Canary black',
    description: 'Amazing movie Ntigucike.... 😊',
    interpreter_name: 'Rocky',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/canaryblack.webp',
    poster_url: '/canaryblack.webp',
    image_url: '/canaryblack.webp',
    video_url: 'https://hglink.to/v5clqotx86ye',
    download_url:
      'https://www.mediafire.com/file/v2epmikmoo1ug86/BLACK+CARINARY.MP4/file',
    youtube_trailer_url: 'https://hglink.to/6op9gnt30vdo',
  },

  {
    id: '10113',
    title: 'SAGATWA 1 (THE GODS MUST BE CRAZY)',
    description: 'Amazing movie Ntigucike.... 😊',
    interpreter_name: 'YANGA',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/the gods.jpg',
    poster_url: '/the gods.jpg',
    image_url: '/the gods.jpg',
    video_url: 'https://hglink.to/6op9gnt30vdo',
    download_url:
      'https://www.mediafire.com/file/rdxnc7947vt47xq/SAGATWA_I.mp4/file',
    youtube_trailer_url: 'https://hglink.to/6op9gnt30vdo',
  },

  {
    id: '10134',
    title: 'SAGATWA 2 (THE GODS MUST BE CRAZY)',
    description: 'Amazing movie Ntigucike.... 😊',
    interpreter_name: 'YANGA',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/the gods.jpg',
    poster_url: '/the gods.jpg',
    image_url: '/the gods.jpg',
    video_url: 'https://hglink.to/prqxw3ia68ic',
    download_url:
      'https://www.mediafire.com/file/3pvoscuit7u814z/SAGATWA_II.mp4/file',
    youtube_trailer_url: 'https://hglink.to/prqxw3ia68ic',
  },

  {
    id: '1012222',
    title: 'Men of honor B',
    description: 'Amazing movie Ntigucike.... 😊',
    interpreter_name: 'Rocky',
    is_featured: true,
    thumbnail_url: '/Menofww.webp',
    poster_url: '/Menofww.webp',
    image_url: '/Menofww.webp',
    video_url: 'https://hglink.to/gtn3hnsb1a8e',
    download_url:
      'https://www.mediafire.com/file/tlrr0kp5dzj793l/MEN_OF_HONOR_B.mp4/file',
    youtube_trailer_url: 'https://hglink.to/gtn3hnsb1a8e',
  },

  {
    id: 's109',
    title: 'Men of honor A',
    description: 'Amazing movie Ntigucike.... 😊',
    interpreter_name: 'Rocky',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/men of honor.jpg',
    poster_url: '/men of honor.jpg',
    image_url: '/men of honor.jpg',
    video_url: 'https://hglink.to/s6gdz8cweyhc',
    download_url:
      'https://www.mediafire.com/file/9ywpm30nf2nsl8c/MEN_OF_HONOR_A.mp4/file',
    youtube_trailer_url: 'https://hglink.to/s6gdz8cweyhc',
  },

  {
    id: 's95',
    title: 'NOBODY 1 A',
    description: 'Amazing movie Ntigucike😊',
    interpreter_name: 'Rocky',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/nobody.webp',
    poster_url: '/nobody.webp',
    image_url: '/nobody.webp',
    video_url: 'https://hglink.to/exu1007iflaf',
    download_url:
      'https://www.mediafire.com/file/es0031nji6afht0/NOBODY_PART_1-.mp4/file',
    youtube_trailer_url: 'https://hglink.to/exu1007iflaf',
  },

  {
    id: '109',
    title: 'JAAT B',
    description: 'NTUCIKWE NIYI..😊 ',
    interpreter_name: 'Rocky',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/jaat.jpg',
    poster_url: '/jaat.jpg',
    image_url: '/jaat.jpg',
    download_url:
      'https://www.mediafire.com/file/5h0qrz716hsbuas/JAAT_B__.mp4/file',
    video_url: 'https://hglink.to/yitye7l68wh5',
    youtube_trailer_url: 'https://hglink.to/yitye7l68wh5',
  },

  {
    id: 's96',
    title: 'NOBODY 1 B',
    description: 'Ntigucike...😁 ',
    interpreter_name: 'Rocky',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/nobody.webp',
    poster_url: '/nobody.webp',
    image_url: '/nobody.webp',
    video_url: 'https://hglink.to/3b8btfc8dnax',
    download_url:
      'https://www.mediafire.com/file/9hb4qxa7q0lol4b/NOBODY_PART_1_B.mp4/file',
    youtube_trailer_url: 'https://youtu.be/wZti8QKBWPo?si=xVoUf46r5rH2QViB',
  },
  {
    id: 's2',
    title: 'A WORKING MAN A',
    description: 'Best movie ever.',
    interpreter_name: 'Rocky',
    created_at: '2024-02-12T00:00:00.000Z',
    is_popular: true,
    thumbnail_url: '/workingma.webp',
    poster_url: '/workingma.webp',
    image_url: '/workingma.webp',
    video_url: 'https://hglink.to/lodwr6jn1tbp',
    download_url:
      'https://www.mediafire.com/file/ezr10phz5hni43p/A+WARKING+MAN+A.mp4/file',
    youtube_trailer_url: 'https://youtu.be/zTbgNC42Ops?si=uZ5EnXsdOGrWA98H',
  },

  {
    id: '108',
    title: 'A WORKING MAN B',
    description:
      'Working Man (2019) is a poignant American drama directed by Robert Jury, exploring themes of identity, purpose, and community in the face of economic hardship.',
    interpreter_name: 'Rocky',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/workingma.webp',
    poster_url: '/workingma.webp',
    image_url: '/workingma.webp',
    download_url:
      'https://www.mediafire.com/file/zusyab9bl6e1x73/A_WORKING_MAN_B.mp4/file',
    video_url: 'https://hglink.to/dy1somwlbv6e',
    youtube_trailer_url: 'https://youtu.be/zTbgNC42Ops?si=WDAYyrpAC6Ea7hXi',
  },

  {
    id: '105',
    title: 'WAR A',
    description:
      'War is a high-octane Indian action-thriller directed by Siddharth Anand, starring Hrithik Roshan and Tiger Shroff. The film follows Major Kabir Dhaliwal, a skilled Indian intelligence officer who goes rogue after a mission to capture a terrorist goes awry.',
    interpreter_name: 'Rocky',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/downloadwar.jpg',
    poster_url: '/waeposter.jpg',
    image_url: '/waeposter.jpg',
    download_url:
      'https://www.mediafire.com/file/v8h5xa9j908244w/War_India_A.mp4/file',
    video_url: 'https://hglink.to/l3by3hukovfh',
    youtube_trailer_url: 'https://youtu.be/oGneAab3e88?si=Zbnw611-U7AT8g43',
  },

  {
    id: '106',
    title: 'WAR B',
    description:
      'War is a high-octane Indian action-thriller directed by Siddharth Anand, starring Hrithik Roshan and Tiger Shroff. The film follows Major Kabir Dhaliwal, a skilled Indian intelligence officer who goes rogue after a mission to capture a terrorist goes awry.',
    interpreter_name: 'Rocky',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/downloadwar.jpg',
    poster_url: '/waeposter.jpg',
    image_url: '/waeposter.jpg',
    download_url:
      'https://www.mediafire.com/file/ft5vhwsjq2h3ha9/War_India_B.mp4/file',
    video_url: 'https://hglink.to/1gnxdc3i2v5a',
    youtube_trailer_url: 'https://youtu.be/oGneAab3e88?si=Zbnw611-U7AT8g43',
  },

  {
    id: '107',
    title: 'WAR C',
    description:
      'War is a high-octane Indian action-thriller directed by Siddharth Anand, starring Hrithik Roshan and Tiger Shroff. The film follows Major Kabir Dhaliwal, a skilled Indian intelligence officer who goes rogue after a mission to capture a terrorist goes awry.',
    interpreter_name: 'Rocky',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/downloadwar.jpg',
    poster_url: '/waeposter.jpg',
    image_url: '/waeposter.jpg',
    download_url:
      'https://www.mediafire.com/file/znoti3fiwpwl9n6/War_C_Hd.mp4/file',
    video_url: 'https://hglink.to/lpnx8y0tlauy',
    youtube_trailer_url: 'https://youtu.be/oGneAab3e88?si=Zbnw611-U7AT8g43',
  },

  {
    id: 'BallerinaB',
    title: 'Ballerina B',
    description: 'Amazing movie ever ',
    interpreter_name: 'Rocky',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/ballerinaOg.webp',
    poster_url: '/ballerinaOg.webp',
    image_url: '/ballerinaOg.webp',
    download_url:
      'https://www.mediafire.com/file/3inbvghuysxj50j/BALLERINA_B.mp4/ilef',
    video_url: 'https://hglink.to/jznrgf4v9wry',
    youtube_trailer_url: 'https://youtu.be/b9Rr9ygb-ac?si=PdIj9yTEpt4gIeqd',
  },

  {
    id: 's90',
    title: 'Straw A',
    description:
      'Straw is a 2025 drama film directed by Tyler Perry and starring Taraji P. Henson, about a desperate single mother, Janiyah, whose world unravels after a series of escalating misfortunes, culminating in a bank standoff.',
    interpreter_name: 'Rocky',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/straw1.webp',
    poster_url: '/straw1.webp',
    image_url: '/straw1.webp',
    video_url: 'https://hglink.to/8ura1dtea1yy',

    download_url:
      'https://www.mediafire.com/file/8cu33ck3lqmjops/STRAW_B.mp4/file',
    youtube_trailer_url: 'https://youtu.be/k1vWhii4tkE?si=RTSvjvhkx2M7MTm_',
  },

  {
    id: 's91',
    title: 'Straw B',
    description:
      'Straw is a 2025 drama film directed by Tyler Perry and starring Taraji P. Henson, about a desperate single mother, Janiyah, whose world unravels after a series of escalating misfortunes, culminating in a bank standoff.',
    interpreter_name: 'Rocky',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/straw1.webp',
    poster_url: '/straw1.webp',
    image_url: '/straw1.webp',
    video_url: 'https://hglink.to/j74rvb5zlyk0',
    download_url:
      'https://www.mediafire.com/file/8cu33ck3lqmjops/STRAW_B.mp4/file',
    youtube_trailer_url: 'https://youtu.be/k1vWhii4tkE?si=RTSvjvhkx2M7MTm_',
  },

  {
    id: 's92',
    title: 'ACCIDENT MAN ASSASSINS HOLIDAY',
    description:
      'Mike Fallon (Scott Adkins) moves to Malta to decompress after the events of the first film and works as a freelance hitman, fighting martial artist Wong Siu-ling to stay sharp. He is drawn back into action when his mentor, Big Ray (Ray Stevenson), reveals   bar and needs help protecting his son and saving Finicky Fred, forcing Mike to take on the world',
    interpreter_name: 'Rocky',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/accident.jpg',
    poster_url: '/accident.jpg',
    image_url: '/accident.jpg',
    video_url: 'https://hglink.to/iud4hpo2i5b2',
    download_url:
      'https://www.mediafire.com/file/j6wkv3kcej9t010/ACCIDENT_MAN_ASSASSINS_HOLIDAY.mp4/file',
    youtube_trailer_url: 'https://youtu.be/YGR4HVtNNYM?si=t-RT2zMnAIXGM_Hd',
  },

  {
    id: 's93',
    title: 'THE AGE OF ADALINE A',
    description: ' ',
    interpreter_name: 'Rocky',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/adeline.jpg',
    poster_url: '/adeline.jpg',
    image_url: '/adeline.jpg',
    video_url: 'https://hglink.to/256vgg8bht9r',
    download_url:
      'https://www.mediafire.com/file/c3zp7yg07dbfz9y/THE_AGE_OF_ADALINE_A.mp4/file',
    youtube_trailer_url: 'https://youtu.be/7UzSekc0LoQ?si=StjTs8DespqhyzBq',
  },

  {
    id: 's94',
    title: 'THE AGE OF ADALINE B',
    description: ' ',
    interpreter_name: 'Rocky',
    created_at: '2024-02-12T00:00:00.000Z',
    thumbnail_url: '/adeline.jpg',
    poster_url: '/adeline.jpg',
    image_url: '/adeline.jpg',
    video_url: 'https://hglink.to/nl4kvb1ujbc9',
    download_url:
      'https://www.mediafire.com/file/ii2fdw0d0x37lis/THE_AGE_OF_ADALINE_B.mp4/file',
    youtube_trailer_url: 'https://youtu.be/7UzSekc0LoQ?si=StjTs8DespqhyzBq',
  },

  {
    id: 's1',
    title: 'Ballerina',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'Rocky',
    created_at: '2025-01-01T00:00:00.000Z',
    thumbnail_url: '/ballerinaOg.webp',
    poster_url: '/ballerinaOg.webp',
    image_url: '/ballerinaOg.webp',
    backdrop_url: '/ballerinaOg.webp',
    video_url: 'https://hglink.to/b9i9la0ewhjo',
    youtube_trailer_url: 'https://youtu.be/0FSwsrFpkbw?si=_1SY_posJ_tpXjQk',
  },

  {
    id: 's1+',
    title: 'NOBODY 2 A',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'Rocky',
    created_at: '2025-01-01T00:00:00.000Z',
    is_popular: true,
    thumbnail_url: '/nobody.webp',
    poster_url: '/nobody.webp',
    image_url: '/nobody.webp',
    backdrop_url: '/nobody.webp',
    video_url: 'https://hglink.to/23c6gz2rsc81',
    download_url:
      'https://www.mediafire.com/file/qdpr84agqrv8ar1/NOBODY_PART_2_A.mp4/file',
    youtube_trailer_url: 'https://youtu.be/-5X2pt95cIo?si=th6aaMtfv1kHhdLL',
  },

  {
    id: 's1++',
    title: 'NOBODY 2 B',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'Rocky',
    created_at: '2025-01-01T00:00:00.000Z',
    thumbnail_url: '/nobody.webp',
    poster_url: '/nobody.webp',
    image_url: '/nobody.webp',
    backdrop_url: '/nobody.webp',
    video_url: 'https://hglink.to/4wwi6mbwr80y',
    download_url:
      'https://www.mediafire.com/file/d5lq25ffmv8f2e6/NOBODY_PART_2_B.mp4/file',
    youtube_trailer_url: 'https://youtu.be/-5X2pt95cIo?si=th6aaMtfv1kHhdLL',
  },

  {
    id: 's3',
    title: 'JAAT A',
    description: 'A fresh indian movie.',
    interpreter_name: 'Rocky',
    created_at: '2024-03-20T00:00:00.000Z',
    thumbnail_url: '/jaat.jpg',
    poster_url: '/jaat.jpg',
    image_url: '/jaat.jpg',
    download_url:
      'https://www.mediafire.com/file/c8c97xxapoi6urx/JAAT_A.mp4/file',
    video_url: 'https://hglink.to/957165f3cx4s',
    youtube_trailer_url: 'https://youtu.be/-I5kX9b9rGc?si=xCeJqxK9vCsOJ8nG',
  },
  {
    id: 's4',
    title: 'Furiosa  A Mad Max Saga',
    description: 'Best movie ever.',
    interpreter_name: 'Rocky',
    created_at: '2024-04-05T00:00:00.000Z',
    thumbnail_url: '/furioswa.jpg',
    poster_url: '/furioswa.jpg',
    image_url: '/furioswa.jpg',
    video_url: 'https://hglink.to/tytkmbs5t5ot',
    youtube_trailer_url: 'https://youtu.be/XJMuhwVlca4?si=3lpPzFFqAsrm_H62',
  },
  {
    id: 's5',
    title: 'Mission Impossible dead reckoning B',
    description: 'Mission Impossible',
    interpreter_name: 'Rocky',
    created_at: '2024-05-15T00:00:00.000Z',
    thumbnail_url: '/missionB.jpg',
    poster_url: '/missionB.jpg',
    image_url: '/missionB.jpg',
    video_url: 'https://hglink.to/e/qrn2xt5oxp8i',
    youtube_trailer_url: 'https://youtu.be/avz06PDqDbM?si=0LqnWR0Snl-IljZR',
  },
  {
    id: 's6',
    title: 'The Covenant War',
    description: 'High-energy picks to kick things off.',
    interpreter_name: 'Dylan',
    created_at: '2024-06-10T00:00:00.000Z',
    thumbnail_url: '/covenant.jpg',
    poster_url: '/covenant.jpg',
    image_url: '/covenant.jpg',
    video_url: 'https://hglink.to/e/or3y91d8atrf',
    youtube_trailer_url: 'https://youtu.be/02PPMPArNEQ?si=awfiGxqIj_X4lr3T',
  },
  {
    id: 's7',
    title: 'Fast and fury 12 hours',
    description: 'Light-hearted laughs while you wait.',
    interpreter_name: 'Rocky',
    created_at: '2024-07-22T00:00:00.000Z',
    thumbnail_url: '/fury12.jpg',
    poster_url: '/fury12.jpg',
    image_url: '/fury12.jpg',
    video_url: 'https://hglink.to/qtkx1utmna8i',
    youtube_trailer_url: 'https://youtu.be/0ax2NfdJEkM?si=ogTA1JvzLHBObNGB',
  },
  {
    id: 's8',
    title: '24 hours to live A',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'SAVIMBI',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/24hours.jpg',
    poster_url: '/24hours.jpg',
    image_url: '/24hours.jpg',
    video_url: 'https://hglink.to/tykqxwd3nkex',
    download_url:
      'https://www.mediafire.com/file/pm7k68hqp0kwqyi/24_HOURS_TO_LIVE_A_by_savimb.mp4/file',
    youtube_trailer_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  },

  {
    id: 's8-',
    title: '24 hours to live B',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'SAVIMBI',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/24hours.jpg',
    poster_url: '/24hours.jpg',
    image_url: '/24hours.jpg',
    video_url: 'https://hglink.to/tykqxwd3nkex',
    download_url:
      'https://www.mediafire.com/file/q0ul6eb9x9cyro6/24_HOURS_TO_LIVE_B_by_savimb.mp4/file',
    youtube_trailer_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  },

  {
    id: 's9',
    title: 'warhorse one',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'Dylan',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/war1.jpeg',
    poster_url: '/war1.jpeg',
    image_url: '/war1.jpeg',
    video_url: 'https://hglink.to/e/o1whn7yf520u',
    download_url:
      'https://www.mediafire.com/file/wkk5mk0tsouixf7/1.HORSEWAR_ONE.mp4/file',
    youtube_trailer_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  },

  {
    id: 's10',
    title: 'AMBULANCE',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'JUNIOR GITI',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/AmbulanceX.webp',
    poster_url: '/AmbulanceX.webp',
    image_url: '/AmbulanceX.webp',
    video_url: 'https://hglink.to/wjfr5u3kuy79',
    youtube_trailer_url: 'https://youtu.be/7NU-STboFeI?si=tWC4ghQba7s7M1Rq',
  },

  {
    id: 's11',
    title: 'Fistful of Vengeance',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'JUNIOR GITI',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/fist.jpg',
    poster_url: '/fist.jpg',
    image_url: '/fist.jpg',
    video_url: 'https://hglink.to/yb285kh53amw',
    youtube_trailer_url: 'https://youtu.be/vC_n_L1KGbo?si=Fm_576pmU5aB91UD',
  },

  {
    id: 's12',
    title: 'Johnny English 1 ',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'JUNIOR GITI',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/johnny1.jpg',
    poster_url: '/johnny1.jpg',
    image_url: '/johnny1.jpg',
    video_url: 'https://hglink.to/moysnstxma15',
    youtube_trailer_url: 'https://youtu.be/lFmFwCRLsK4?si=MWchYGR9XVlBxamL',
  },

  {
    id: 's13',
    title: 'Plane',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'JUNIOR GITI',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/plane.jpg',
    poster_url: '/plane.jpg',
    image_url: '/plane.jpg',
    video_url: 'https://hglink.to/zajv6d0nrsn2',
    youtube_trailer_url: 'https://youtu.be/M25zXBIUVr0?si=GG-jaVYZqVpyXSfd',
  },

  {
    id: 's14',
    title: 'The Witch',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/witch.jpg',
    poster_url: '/witch.jpg',
    image_url: '/witch.jpg',
    video_url: 'https://hglink.to/iezkuuwli02v',
    youtube_trailer_url: 'https://youtu.be/eYJuGhT5nYs?si=rv3MS8sjTTeio2U8',
  },

  {
    id: 's15',
    title: 'Home Sweet Home  Rebirth',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/rebirth.jpg',
    poster_url: '/rebirth.jpg',
    image_url: '/rebirth.jpg',
    video_url: 'https://hglink.to/2fd9cqf8j3gb',
    youtube_trailer_url: 'https://youtu.be/8pYI0jNXSqI?si=9EAZCFVSgCCYt9-H',
  },

  {
    id: 's16',
    title: 'It Feeds',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/feeds.jpg',
    poster_url: '/feeds.jpg',
    image_url: '/feeds.jpg',
    video_url: 'https://hglink.to/u52sqxbn4c6s',
    youtube_trailer_url: 'https://youtu.be/spLyHdJ_SyE?si=y2uXavrrlW0lahJX',
  },

  {
    id: 's17',
    title: 'Fury 12 Hours',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/fury.jpg',
    poster_url: '/fury.jpg',
    image_url: '/fury.jpg',
    video_url: 'https://hglink.to/qtkx1utmna8i',
    youtube_trailer_url: 'https://youtu.be/mKJucnucZ5M?si=siqRGFtjODlNIKNj',
  },

  {
    id: 's18',
    title: 'Brick',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/brick.jpg',
    poster_url: '/brick.jpg',
    image_url: '/brick.jpg',
    video_url: 'https://hglink.to/14npq1esngdz',
    youtube_trailer_url: 'https://youtu.be/fmi4Qc-cvis?si=cUmQCWK03FDPx5gh',
  },

  {
    id: 's19',
    title: 'Brick',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/amaran.jpg',
    poster_url: '/amaran.jpg',
    image_url: '/amaran.jpg',
    video_url: 'https://hglink.to/5p6ev2oofvb7',
    youtube_trailer_url: 'https://youtu.be/H7FT-d4YA74?si=NK1PR0znQe1Vqbbl',
  },

  {
    id: 's20',
    title: '24 Hours to Live',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/hours.jpg',
    poster_url: '/hours.jpg',
    image_url: '/hours.jpg',
    video_url: 'https://hglink.to/tykqxwd3nkex',
    youtube_trailer_url: 'https://youtu.be/PfeQX80tjdQ?si=Wx5vcKWtXwzP50PE',
  },

  // {
  //   id: 's21',
  //   title: 'Havoc',
  //   description: 'Gripping stories at a glance.',
  //   interpreter_name: 'GAHEZA',
  //   created_at: '2024-08-30T00:00:00.000Z',
  //   thumbnail_url: '/havoc.webp',
  //   poster_url: '/havoc.webp',
  //   image_url: '/havoc.webp',
  //   video_url: 'https://hglink.to/59qmk7lvvudb',
  //   youtube_trailer_url: 'https://youtu.be/6txjTWLoSc8?si=8lOGzv-bjEhGaZKj',
  // },

  {
    id: 's22',
    title: 'Flight Risk',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/flight.jpg',
    poster_url: '/flight.jpg',
    image_url: '/flight.jpg',
    video_url: 'https://hglink.to/nnnp8f4kxw77',
    youtube_trailer_url: 'https://youtu.be/ojC9JBuccJA?si=reaoMi-xOdiljl6O',
  },

  {
    id: 's23',
    title: 'Drop',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/drop.jpg',
    poster_url: '/drop.jpg',
    image_url: '/drop.jpg',
    video_url: 'https://hglink.to/fej9udmslz7c',
    youtube_trailer_url: 'https://youtu.be/bs_nFwh5eJw?si=BWa344KQD4NfkkbN',
  },

  {
    id: 's24',
    title: 'Contraataque',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'SANKARA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/contra.jpg',
    poster_url: '/contra.jpg',
    image_url: '/contra.jpg',
    video_url: 'https://hglink.to/8updb5fyevyd',
    youtube_trailer_url: 'https://youtu.be/bs_nFwh5eJw?si=BWa344KQD4NfkkbN',
  },

  {
    id: 's25',
    title: 'In the Lost Lands',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/lands.jpg',
    poster_url: '/lands.jpg',
    image_url: '/lands.jpg',
    video_url: 'https://hglink.to/swng2v5cifeq',
    youtube_trailer_url: 'https://youtu.be/b9UC1szqE_k?si=n94iJZQ5qKtv-cjt',
  },

  {
    id: 's26',
    title: 'iHostage',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/hostage.jpg',
    poster_url: '/hostage.jpg',
    image_url: '/hostage.jpg',
    video_url: 'https://hglink.to/cbisitgp04k1',
    youtube_trailer_url: 'https://youtu.be/Dhg-3ME2L6M?si=g0O_PRwMC4-PCcb4',
  },

  {
    id: 's27',
    title: 'Kill',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/kill.jpg',
    poster_url: '/kill.jpg',
    image_url: '/kill.jpg',
    video_url: 'https://hglink.to/4vjfnwcj5qrb',
    youtube_trailer_url: 'https://youtu.be/da7lKeeS67c?si=anUYA55Qle_gzY9K',
  },

  {
    id: 's28',
    title: 'Kill Boksoon ',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/bookson.jpg',
    poster_url: '/bookson.jpg',
    image_url: '/bookson.jpg',
    video_url: 'https://hglink.to/o40pp6blwumk',
    youtube_trailer_url: 'https://youtu.be/70e5RjgkHjU?si=iY4Q82MkCozjPxyJ',
  },

  {
    id: 's29',
    title: 'Last Breath',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/breaath.jpg',
    poster_url: '/breaath.jpg',
    image_url: '/breaath.jpg',
    video_url: 'https://hglink.to/0tvgocbbfbe0',
    youtube_trailer_url: 'https://youtu.be/sNMyooXZZTM?si=AGLKFvTwd-NhB9ZZ',
  },

  {
    id: 's30',
    title: 'The last bullet',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/bullet.jpg',
    poster_url: '/bullet.jpg',
    image_url: '/bullet.jpg',
    video_url: 'https://hglink.to/3677ycukjem8',
    youtube_trailer_url: 'https://youtu.be/r2u9GifyDg0?si=tapaissLZN1EcHEZ',
  },

  {
    id: 's31',
    title: 'No Way Up',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/way.jpg',
    poster_url: '/way.jpg',
    image_url: '/way.jpg',
    video_url: 'https://hglink.to/3677ycukjem8',
    youtube_trailer_url: 'https://youtu.be/r2u9GifyDg0?si=tapaissLZN1EcHEZ',
  },

  {
    id: 's32',
    title: 'Rosario',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/rosario.jpg',
    poster_url: '/rosario.jpg',
    image_url: '/rosario.jpg',
    video_url: 'https://hglink.to/mjfo2i1174pj',
    youtube_trailer_url: 'https://youtu.be/ksM0rCILPqg?si=b6FzPdugC8wGo9YK',
  },

  {
    id: 's33',
    title: 'Snow White',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/snowwhite.jpg',
    poster_url: '/snowwhite.jpg',
    image_url: '/snowwhite.jpg',
    video_url: 'https://hglink.to/57c3bxak6jhb',
    youtube_trailer_url: 'https://youtu.be/iV46TJKL8cU?si=5XEjDTmstb2It3wh',
  },

  {
    id: 's34',
    title: 'The Diplomat',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/diplomat.jpg',
    poster_url: '/diplomat.jpg',
    image_url: '/diplomat.jpg',
    video_url: 'https://hglink.to/wc4f6yaq35hu',
    youtube_trailer_url: 'https://youtu.be/lV6sJlBbhPs?si=b2bRkM9D-rfNibxO',
  },

  {
    id: 's35',
    title: 'The Gorge',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/gorge.jpg',
    poster_url: '/gorge.jpg',
    image_url: '/gorge.jpg',
    video_url: 'https://hglink.to/zwr60nahxn56',
    youtube_trailer_url: 'https://youtu.be/rUSdnuOLebE?si=ydb_tWjpJrdhk3sk',
  },

  {
    id: 's36',
    title: 'Heart of Stone',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/stone.jpg',
    poster_url: '/stone.jpg',
    image_url: '/stone.jpg',
    video_url: 'https://hglink.to/7bo47bpg8at6',
    youtube_trailer_url: 'https://youtu.be/XuDwndGaCFo?si=FJOmOboNS4DFmIXZ',
  },

  {
    id: 's37',
    title: 'The Last Supper',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/supper.jpg',
    poster_url: '/supper.jpg',
    image_url: '/supper.jpg',
    video_url: 'https://hglink.to/1mrj3guot1u6',
    youtube_trailer_url: 'https://youtu.be/-jwAbai7k0s?si=U_WgZ6lOSahgIDO-',
  },

  {
    id: 's38',
    title: 'Tuhog',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/tuhog.jpg',
    poster_url: '/tuhog.jpg',
    image_url: '/tuhog.jpg',
    video_url: 'https://hglink.to/6au3k0l3xaic',
    youtube_trailer_url: 'https://youtu.be/C0BvkC3fQUo?si=B3V83KaExv1Hpk67',
  },

  {
    id: 's39',
    title: "Tyler Perry's Duplicity",
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/perry.jpg',
    poster_url: '/perry.jpg',
    image_url: '/perry.jpg',
    video_url: 'https://hglink.to/afq3dd7hvvdq',
    youtube_trailer_url: 'https://youtu.be/i6NvYfJwq-U?si=mn-V-63smz0SOWT3',
  },

  {
    id: 's40',
    title: 'Until Dawn',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'GAHEZA',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/down.jpg',
    poster_url: '/down.jpg',
    image_url: '/down.jpg',
    video_url: 'https://hglink.to/hsmj62und74o',
    youtube_trailer_url: 'https://youtu.be/2b3vBaINZ7w?si=vceZHfd4fMU9H31s',
  },
  {
    id: 's42',
    title: 'Freelance',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/freelance.jpg',
    poster_url: '/freelance.jpg',
    image_url: '/freelance.jpg',
    video_url: 'https://hglink.to/w0j6vqkumxmt',
    youtube_trailer_url: 'https://youtu.be/BrqWlOzm2Iw?si=_nIDXuJZWRrOZDvS',
  },

  {
    id: 's43',
    title: 'Fateh',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/fateh.jpg',
    poster_url: '/fateh.jpg',
    image_url: '/fateh.jpg',
    video_url: 'https://hglink.to/t8t9ddsgp1t2',
    youtube_trailer_url: 'https://youtu.be/5efGUAV9Vv8?si=V-Z8ZacXpiSBUYr3',
  },

  {
    id: 's44',
    title: 'Jawan',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/jawan.jpg',
    poster_url: '/jawan.jpg',
    image_url: '/jawan.jpg',
    video_url: 'https://hglink.to/t9u0gvfae7aj',
    youtube_trailer_url: 'https://youtu.be/MWOlnZSnXJo?si=Pix4xlS_XYMNKC_E',
  },

  {
    id: 's45',
    title: 'John Wick  Chapter 4',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/wich4.jpg',
    poster_url: '/wich4.jpg',
    image_url: '/wich4.jpg',
    video_url: 'https://hglink.to/ix01rjjpvb43',
    youtube_trailer_url: 'https://youtu.be/qEVUtrk8_B4?si=RvZT_7zhiV4zjhhx',
  },

  {
    id: 's46',
    title: 'KEEPER',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/keeper.jpg',
    poster_url: '/keeper.jpg',
    image_url: '/keeper.jpg',
    video_url: 'https://hglink.to/q484hf72fcw3',
    youtube_trailer_url: 'https://youtu.be/nKA_N_pEkww?si=C0FyZK9sVAyUZmsd',
  },

  {
    id: 's47',
    title: 'Kesari Chapter 2  The Untold Story of Jallianwala Bagh',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/kesaari.webp',
    poster_url: '/kesaari.webp',
    image_url: '/kesaari.webp',
    video_url: 'https://hglink.to/78qfdhr0to8f',
    youtube_trailer_url: 'https://youtu.be/r-7g08INMSI?si=jRQy_HHIngnlK6tZ',
  },

  {
    id: 's48',
    title: 'Kisi Ka Bhai Kisi Ki Jaan',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/kisi.jpg',
    poster_url: '/kisi.jpg',
    image_url: '/kisi.jpg',
    video_url: 'https://hglink.to/1atemzdabfdb',
    youtube_trailer_url: 'https://youtu.be/bsi8_9EoYyg?si=NFirB1_xzd4mpVMX',
  },

  {
    id: 's49',
    title: 'Laal Singh Chaddha',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/laal.jpg',
    poster_url: '/laal.jpg',
    image_url: '/laal.jpg',
    video_url: 'https://hglink.to/nuajt7hd2fvo',
    youtube_trailer_url: 'https://youtu.be/R6savS7m0Fg?si=H6CunswEpdnOv1GL',
  },

  {
    id: 's50',
    title: 'Land of Bad',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/landofbad.jpg',
    poster_url: '/landofbad.jpg',
    image_url: '/landofbad.jpg',
    video_url: 'https://hglink.to/rn66cefxcnyk',
    youtube_trailer_url: 'https://youtu.be/yTFazxfrXVw?si=JLAzKxPsg0coAhYL',
  },

  {
    id: 's51',
    title: 'LOCKED',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/locked.jpg',
    poster_url: '/locked.jpg',
    image_url: '/locked.jpg',
    video_url: 'https://hglink.to/s78tqi27svj7',
    youtube_trailer_url: 'https://youtu.be/MHAf0S9kEZw?si=jW4yyiwZCSG1ce4C',
  },

  {
    id: 's52',
    title: 'Luther  The Fallen Sun',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/luther.jpg',
    poster_url: '/luther.jpg',
    image_url: '/luther.jpg',
    video_url: 'https://hglink.to/yp6mg2vficng',
    youtube_trailer_url: 'https://youtu.be/EGK5qtXuc1Q?si=xe4o2AT5HfXaft8r',
  },

  {
    id: 's53',
    title: 'Major',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/major.jpg',
    poster_url: '/major.jpg',
    image_url: '/major.jpg',
    video_url: 'https://hglink.to/bxfbbf4c0j9u',
    youtube_trailer_url: 'https://youtu.be/PAv1Ke07QAM?si=GgbNEYistyZJW01j',
  },

  {
    id: 's54',
    title: 'Mission  Impossible 7 - Dead Reckoning Part One',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/mission1.jpg',
    poster_url: '/mission1.jpg',
    image_url: '/mission1.jpg',
    video_url: 'https://hglink.to/22jy477klw6s',
    youtube_trailer_url: 'https://youtu.be/avz06PDqDbM?si=8gFJqDN1OVMBKpBn',
  },

  {
    id: 's55',
    title: 'R I P D  2  Rise of the Damned',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/damned.jpg',
    poster_url: '/damned.jpg',
    image_url: '/damned.jpg',
    video_url: 'https://hglink.to/da9abyb75gvm',
    youtube_trailer_url: 'https://youtu.be/IgogIezu6l4?si=QFf5N6n8GwDcPIbV',
  },

  {
    id: 's56',
    title: 'Redeeming Love',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/redeeming.jpg',
    poster_url: '/redeeming.jpg',
    image_url: '/redeeming.jpg',
    video_url: 'https://hglink.to/si3pdwy9ol3v',
    youtube_trailer_url: 'https://youtu.be/_8RIlIOd_us?si=BfeMNkvMVfpVIXw_',
  },

  {
    id: 's57',
    title: 'Retribution',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/retribution.jpg',
    poster_url: '/retribution.jpg',
    image_url: '/retribution.jpg',
    video_url: 'https://hglink.to/xj2eiiyqk8w4',
    youtube_trailer_url: 'https://youtu.be/jzQn0-WH4WM?si=n47bYgqWUZz380ni',
  },
  {
    id: 's59',
    title: 'Singham Again',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/singam.jpg',
    poster_url: '/singam.jpg',
    image_url: '/singam.jpg',
    video_url: 'https://hglink.to/eh8ndkgxac9d',
    youtube_trailer_url: 'https://youtu.be/MD7v0-igVIM?si=cxxX6QUTFCYjuEAx',
  },

  {
    id: 's60',
    title: 'Sinners',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/sinners.jpg',
    poster_url: '/sinners.jpg',
    image_url: '/sinners.jpg',
    video_url: 'https://hglink.to/6au0vfd9k02t',
    youtube_trailer_url: 'https://youtu.be/bKGxHflevuk?si=9JAFXFnwBrN2GCM6',
  },

  {
    id: 's61',
    title: 'Sisu',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/sisu.jpg',
    poster_url: '/sisu.jpg',
    image_url: '/sisu.jpg',
    video_url: 'https://hglink.to/dtfkpo285zvz',
    youtube_trailer_url: 'https://youtu.be/2NnPzpuU5ao?si=kPvG10PHyTEfPFva',
  },

  {
    id: 's62',
    title: 'SKVY3388',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/affinity.jpg',
    poster_url: '/affinity.jpg',
    image_url: '/affinity.jpg',
    video_url: 'https://hglink.to/a1dtq218s6ot',
    youtube_trailer_url: 'https://youtu.be/i5EognW_9Lk?si=ivlJhAeX4vzrWnf_',
  },

  {
    id: 's63',
    title: 'The Equalizer 3',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/equalizer.jpg',
    poster_url: '/equalizer.jpg',
    image_url: '/equalizer.jpg',
    video_url: 'https://hglink.to/l3umbc6d66u5',
    youtube_trailer_url: 'https://youtu.be/19ikl8vy4zs?si=g7FpnDmkTdaHoBJU',
  },

  {
    id: 's64',
    title: 'The Family Plan',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/family.jpg',
    poster_url: '/family.jpg',
    image_url: '/family.jpg',
    video_url: 'https://hglink.to/h38ienf6qfs3',
    youtube_trailer_url: 'https://youtu.be/ns8weNznn1Y?si=VliD78g8211NZMJm',
  },

  {
    id: 's65',
    title: 'The Gray Man',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/gray.jpg',
    poster_url: '/gray.jpg',
    image_url: '/gray.jpg',
    video_url: 'https://hglink.to/773j68rsthok',
    youtube_trailer_url: 'https://youtu.be/BmllggGO4pM?si=b58m3YleB_WR5pC-',
  },

  {
    id: 's66',
    title: 'The Mother',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/mother.jpg',
    poster_url: '/mother.jpg',
    image_url: '/mother.jpg',
    video_url: 'https://hglink.to/cdm7394q31p8',
    youtube_trailer_url: 'https://youtu.be/8BFdFeOS3oM?si=JdV8LOY8lGBmlX0k',
  },

  {
    id: 's67',
    title: "The Pope's Exorcist",
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/exorcist.jpg',
    poster_url: '/exorcist.jpg',
    image_url: '/exorcist.jpg',
    video_url: 'https://hglink.to/z3fro5a42ctc',
    youtube_trailer_url: 'https://youtu.be/YJXqvnT_rsk?si=dYPMzrUO3N-7JBOx',
  },

  {
    id: 's68',
    title: 'The System',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/system.jpg',
    poster_url: '/system.jpg',
    image_url: '/system.jpg',
    video_url: 'https://hglink.to/r6svp3526eh1',
    youtube_trailer_url: 'https://youtu.be/AFoflf-hass?si=jDDg09d3xAGbQPuL',
  },

  {
    id: 's69',
    title: 'The Tinder Swindler',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/tinder.jpg',
    poster_url: '/tinder.jpg',
    image_url: '/tinder.jpg',
    video_url: 'https://hglink.to/zr8xel7ongnx',
    youtube_trailer_url: 'https://youtu.be/pKXzxzotBo4?si=DtXPxeO97T4TZVGl',
  },

  {
    id: 's70',
    title: 'The woman king',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/woman.jpg',
    poster_url: '/woman.jpg',
    image_url: '/woman.jpg',
    video_url: 'https://hglink.to/km15mrvue74p',
    youtube_trailer_url: 'https://youtu.be/3RDaPV_rJ1Y?si=2TLhVkISN7C-emBO',
  },

  {
    id: 's71',
    title: 'TRAP',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/trap.jpg',
    poster_url: '/trap.jpg',
    image_url: '/trap.jpg',
    video_url: 'https://hglink.to/g9df74ne592e',
    youtube_trailer_url: 'https://youtu.be/hJiPAJKjUVg?si=O4iEdHuv2WBqztJL',
  },

  {
    id: 's72',
    title: 'Violent Night',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/violent.jpg',
    poster_url: '/violent.jpg',
    image_url: '/violent.jpg',
    video_url: 'https://hglink.to/byu7jmsprj2j',
    youtube_trailer_url: 'https://youtu.be/a53e4HHnx_s?si=F2HPnH2xKuiC-TgM',
  },

  {
    id: 's73',
    title: 'Diablo',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/diablo.jpg',
    poster_url: '/diablo.jpg',
    image_url: '/diablo.jpg',
    video_url: 'https://hglink.to/htrixhx9ou6t',
    youtube_trailer_url: 'https://youtu.be/ANKPsCTh0Og?si=4hfFvkdcD_dW1Ngy',
  },

  {
    id: 's74',
    title: 'Exterritorial',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/exterritorial.jpg',
    poster_url: '/exterritorial.jpg',
    image_url: '/exterritorial.jpg',
    video_url: 'https://hglink.to/aufx1fnao1i7',
    youtube_trailer_url: 'https://youtu.be/tlLsFEDHtWs?si=FNSriwUFCvMsHbhY',
  },

  {
    id: 's75',
    title: 'Fountain of Youth',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/fountain.jpg',
    poster_url: '/fountain.jpg',
    image_url: '/fountain.jpg',
    video_url: 'https://hglink.to/9rqgvez6yknn',
    youtube_trailer_url: 'https://youtu.be/1gB9h0ELEf0?si=tHk5mCdFDHJqRpt6',
  },

  {
    id: 's76',
    title: 'G20 ',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/g20.jpg',
    poster_url: '/g20.jpg',
    image_url: '/g20.jpg',
    video_url: 'https://hglink.to/l1j3u5uaofmn',
    youtube_trailer_url: 'https://youtu.be/mhQcpvKHis4?si=2eX4sZfDVVGaRyBl',
  },

  {
    id: 's77',
    title: 'Sikandar',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/sikindar.jpg',
    poster_url: '/sikindar.jpg',
    image_url: '/sikindar.jpg',
    video_url: 'https://hglink.to/xutozu7ld6r5',
    youtube_trailer_url: 'https://youtu.be/in6mSwNbXS0?si=YMFwEUoO5VNMUqR4',
  },

  {
    id: 's78',
    title: 'The Old Guard 2',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/guard.jpg',
    poster_url: '/guard.jpg',
    image_url: '/guard.jpg',
    video_url: 'https://hglink.to/j5o99st2gq4g',
    youtube_trailer_url: 'https://youtu.be/lyivgZ074PY?si=2H9skItxP9LtJ7JI',
  },

  {
    id: 's79',
    title: 'Mission Impossible Final C',
    description: 'Mission Impossiple Final Reckoning',
    interpreter_name: 'Rocky',
    created_at: '2025-01-01T00:00:00.000Z',
    thumbnail_url: '/mission.jpg',
    poster_url: '/mission.jpg',
    image_url: '/mission.jpg',
    backdrop_url: '/mission.jpg',
    video_url: 'https://hglink.to/e/jq1d6h5ex04z ',
    youtube_trailer_url: 'https://youtu.be/fsQgc9pCyDU?si=DlJw5WMC7Ll-hCfN',
  },
  {
    id: 's80',
    title: 'BLACK',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/black.jpg',
    poster_url: '/black.jpg',
    image_url: '/black.jpg',
    video_url: 'https://hglink.to/pxztj5bvqg7t',
    youtube_trailer_url: 'https://youtu.be/By-VTqrdqFI?si=KEah88L9A_3zosWr',
  },

  {
    id: 's81',
    title: 'Black Adam',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/adam.jpg',
    poster_url: '/adam.jpg',
    image_url: '/adam.jpg',
    video_url: 'https://hglink.to/e9qxufl4lqe3',
    youtube_trailer_url: 'https://youtu.be/X0tOpBuYasI?si=O4PQkpIUOPUAOEka',
  },

  {
    id: 's82',
    title: 'Blacklight',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/light.jpg',
    poster_url: '/light.jpg',
    image_url: '/light.jpg',
    video_url: 'https://hglink.to/druc3wq19cvy',
    youtube_trailer_url: 'https://youtu.be/PE04ESdgnHI?si=drHNoKPYqQh9b_-5',
  },

  {
    id: 's83',
    title: 'Burning Betrayal',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/burning.jpg',
    poster_url: '/burning.jpg',
    image_url: '/burning.jpg',
    video_url: 'https://hglink.to/99gmtl3tt6qv',
    youtube_trailer_url: 'https://youtu.be/2I9e8zKFdXI?si=sT6w32yNdiSU1LXa',
  },

  {
    id: 's84',
    title: 'Creed 3 - III',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/creed.webp',
    poster_url: '/creed.webp',
    image_url: '/creed.webp',
    video_url: 'https://hglink.to/1ds2moybw5ce',
    youtube_trailer_url: 'https://youtu.be/AHmCH7iB_IM?si=_trz623wh9ENs7bP',
  },

  {
    id: 's85',
    title: 'Den of Thieves 2',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/den.jpg',
    poster_url: '/den.jpg',
    image_url: '/den.jpg',
    video_url: 'https://hglink.to/6i0cxz63070u',
    youtube_trailer_url: 'https://youtu.be/1kmjAnvFw3I?si=VUi8qjXFySB4Q-gU',
  },

  {
    id: 's86',
    title: 'Deva',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/deva.webp',
    poster_url: '/deva.webp',
    image_url: '/deva.webp',
    video_url: 'https://hglink.to/zrgtkvbnwasn',
    youtube_trailer_url: 'https://youtu.be/3x77q40hATw?si=nPw4xDOS0k9cVmFy',
  },

  {
    id: 's87',
    title: 'Ek Villain Returns',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/villian.jpg',
    poster_url: '/villian.jpg',
    image_url: '/villian.jpg',
    video_url: 'https://hglink.to/6ogv8dvdfqi9',
    youtube_trailer_url: 'https://youtu.be/swPhyd0g6K8?si=IyxX4Pv_OAfzzFZJ',
  },

  {
    id: 's88',
    title: 'Emancipation',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/emanci.jpg',
    poster_url: '/emanci.jpg',
    image_url: '/emanci.jpg',
    video_url: 'https://hglink.to/26kl8lhvqqle',
    youtube_trailer_url: 'https://youtu.be/wafyhTpWpUs?si=E2gBfKd-tIH0FZ44',
  },

  {
    id: 's89',
    title: 'End of the Road',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/end.jpg',
    poster_url: '/end.jpg',
    image_url: '/end.jpg',
    video_url: 'https://hglink.to/bz7zvt1eznc1',
    youtube_trailer_url: 'https://youtu.be/202KkD12AuI?si=yluqRNQDqHNCE1Ue',
  },

  {
    id: 's90',
    title: 'TIME CUT A',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/Time_Cut_film_A.jpg',
    poster_url: '/Time_Cut_film_A.jpg',
    image_url: '/Time_Cut_film_A.jpg',
    video_url: 'https://hglink.to/pdfuxj9rji4z',
    youtube_trailer_url: 'https://youtu.be/bIHnmssfi-A?si=2lFLjkyJzuBWPUYb',
  },

  {
    id: 's90',
    title: 'TIME CUT B',
    description: 'Gripping stories at a glance.',
    interpreter_name: 'ROCKY',
    created_at: '2024-08-30T00:00:00.000Z',
    thumbnail_url: '/Time-cut.webp',
    poster_url: '/Time-cut.webp',
    image_url: '/Time-cut.webp',
    video_url: 'https://hglink.to/6tdke5k1eild',
    youtube_trailer_url: 'https://youtu.be/bIHnmssfi-A?si=2lFLjkyJzuBWPUYb',
  },
];

export default staticMovies;
